[#preface]
[preface]
== 前言

Scheme was introduced in 1975 by Gerald J. Sussman and Guy L. Steele Jr. (<<ref28>>,<<ref29>>),
and was the first dialect of Lisp
to fully support lexical scoping, first-class procedures, and continuations.
In its earliest form
it was a small language
intended primarily for research and teaching,
supporting only a handful of predefined syntactic forms and procedures.
Scheme is now a complete general-purpose programming language,
though it still derives its power
from a small set of key concepts.
Early implementations of the language
were interpreter-based and slow,
but some current Scheme implementations
boast sophisticated compilers
that generate code
on par with
code generated
by the best optimizing compilers
for lower-level languages
such as C and Fortran.

Scheme 是由 Gerald J. Sussman 和 Guy L. Steele Jr. 于 1975 年提出的（<<ref28>>、<<ref29>>），
是首个完全支持 _词法作用域_（Lexical Scoping）、_处理过程优先_（First-class Procedure）
和 _延续_（Continuation）的 Lisp 方言。
在最早的版本中，它只是一门小型语言，主要用于研究和教学，仅支持少数预定义的 _语法形式_ 和 _处理过程_。
虽然它的强大之处仍然源自于一小部分关键概念，但 Scheme 现在已经是一门完全通用的编程语言了。
该语言的早期实现是基于解释器的，运行缓慢，而如今的一些 Scheme 实现拥有复杂巧妙的编译器，
它们生成的代码与为较低级语言（如 C 和 Fortran ）进行最佳优化的编译器所生成的代码不相上下。

[TIP]
.译注
====
可以从文章
link:https://zhuanlan.zhihu.com/p/34064549[柯里化的前生今世（七）：first-class continuation]、
link:https://zhuanlan.zhihu.com/p/180473795[Scheme 的 call/cc]
中初步了解 处理过程优先、延续 等概念。
====

This book is intended to
provide an introduction to the Scheme programming language
but not an introduction to programming in general.
The reader is expected to
have had some experience programming
and to be familiar with terms
commonly associated with computers and programming languages.
Readers unfamiliar with Scheme or Lisp
should also consider reading _The Little Schemer_ <<ref13>>
to become familiar with the concepts of list processing and recursion.
Readers new to programming
should begin with an introductory text on programming.

本书旨在介绍 Scheme 编程语言，而不是一般的编程入门。
读者需具备一定的编程经验，并且熟悉与计算机和编程语言相关的常用术语。
对 Scheme 或 Lisp 不熟悉的读者，应该读一读 _The Little Schemer_ <<ref13>> 以熟悉 _列表处理_ 和 _递归_ 这些概念。
而对于初学编程的读者，则应该先阅读一些编程的入门内容。

Scheme has been standardized both formally and informally.
The _IEEE Standard for the Scheme Programming Language_ <<ref18>>,
describes a formal ANSI/IEEE Standard for Scheme
but dates back to 1991.
A related series of reports,
the "Revised Reports on the Algorithmic Language Scheme,"
document an evolving informal standard
that most implementations support.
The current report in this series
is the "Revised^6^ Report on the Algorithmic Language Scheme" <<ref24>>,
which was completed in 2007.

Scheme 已经被正式和非正式地标准化了。
_《Scheme 编程语言 IEEE 标准》_<<ref18>> 描述了一个正式的 Scheme ANSI/IEEE 标准，但得追溯到1991年。
相关系列的报告--《算法语言 Scheme 修订报告》记录了大多数实现所支持的不断演进的非正式标准。
本系列的最新报告是《算法语言 Scheme 修订报告^6^》<<ref24>> ，于2007年完成。

This book covers the language of the Revised^6^ Report.
It is not intended to supplant the Revised^6^ Report
but rather to
provide a more comprehensive introduction
and reference manual for the language,
with more explanatory text and examples,
suitable more for users than for implementors.
Features specific to particular implementations of Scheme are not included.
In particular,
features specific to the author's Chez Scheme and Petite Chez Scheme implementations
are described separately in the _Chez Scheme User's Guide_ <<ref9>>.
On the other hand,
no book on Scheme would be complete
without some coverage of the interactive top level,
since nearly every Scheme system
supports interactive use in one form or another,
even though the behavior is not standardized by the Revised^6^ Report.
Chapters <<chp_2,2>> and <<chp_3,3>> are thus written
assuming that the reader has available a Scheme implementation
that supports an interactive top level,
with behavior
consistent with the description of the top-level environment
in earlier reports and the IEEE/ANSI standard.

本书涵盖了《修订报告^6^》的内容，但它并不是要取代《修订报告^6^》，而是通过更多的说明性文字和示例，
为该语言提供更全面的介绍，并作为参考手册使用。所以，比起语言实现者，本书更适合该语言的使用者。
针对 Scheme 实现的特定的特性，不包含在本书内，特别是针对作者的 Chez Scheme 和 Petite Chez Scheme 的实现的那些特性，
它们会在《Chez Scheme 用户指南》<<ref9>>
（译注：该书第九版译作在 link:../../chez-scheme-version-9-user-guide/zh/index.html[这里]）中单独描述。
另外，若没有包含对 _交互顶层_ 的介绍，那么，任何关于 Scheme 的书都是不完整的，因为，即使《修订报告^6^》没有对交互方式进行标准化，
但几乎每个 Scheme 系统都会以这种或那种形式支持交互操作。
因此，在撰写 <<chp_2,第二>> 和 <<chp_3,第三>> 章时，便假定读者已经拥有一个支持 _交互顶层_ 的 Scheme 实现，
并且其操作方式与在早期报告以及 IEEE/ANSI 标准中对 _顶层环境_ 的描述一致。

A large number of small- to medium-sized examples
are spread throughout the text,
and one entire chapter is dedicated to
the presentation of a set of longer examples.
Many of the examples show
how a standard Scheme syntactic form or procedure
might be implemented;
others implement useful extensions.
All of the examples
can be entered directly
from the keyboard into an interactive Scheme session.

本书全文中散布了大量中小型示例，并且一个完整的篇章会专门介绍一组较长的例子。
许多示例展示了标准的 Scheme _语法形式_ 和 _处理过程_ 是如何实现的，其他的还实现了一些有用的扩展。
所有示例都可以直接从键盘输入到交互式 Scheme 会话中。

This book is organized into twelve chapters, plus back matter.
<<chp_1,Chapter 1>> describes the properties and features of Scheme
that make it a useful and enjoyable language to use.
<<chp_1,Chapter 1>> also describes
Scheme's notational conventions and the typographical conventions
employed in this book.

加上补充资料，本书共分为十二章。
<<chp_1,第一章>> 描述了让 Scheme 成为一门有用且让人乐于使用的语言的那些特征和特性。
<<chp_1,第一章>> 还介绍了本书采用的 Scheme 符号注解和排版约定。

<<chp_2,Chapter 2>> is an introduction to Scheme programming
for the novice Scheme programmer
that leads the reader
through a series of examples,
beginning with simple Scheme expressions
and working toward progressively more difficult ones.
Each section of <<chp_2,Chapter 2>> introduces
a small set of related features,
and the end of each section contains
a set of exercises for further practice.
The reader will learn the most
from <<chp_2,Chapter 2>>
by sitting at the keyboard
and typing in the examples
and trying the exercises.

<<chp_2,第二章>> 是针对 Scheme 新手程序员的 Scheme 编程简介，
它从简单的 Scheme 表达式开始，引导读者接触一系列示例，并逐步深入更难的表达式。
<<chp_2,第二章>> 的每个章节都会介绍一小部分相关的特性，并在每个章节的末尾安排一组习题，以供进一步练习。
通过在键盘上输入这些示例并尝试这些习题，读者将从 <<chp_2,第二章>> 中获益匪浅。

<<chp_3,Chapter 3>> continues the introduction
but covers more advanced features and concepts.
Even readers with prior Scheme experience
may wish to work through the examples and exercises found there.

<<chp_3,第三章>> 会继续介绍 Scheme，但涵盖了更高级的特性和概念。
即使是先前已经有 Scheme 经验的读者，也会希望去研究里面的示例和习题的。

<<chp_4,Chapter 4>> through <<chp_11,11>> make up the reference portion of the text.
They present each of
Scheme's primitive procedures and syntactic forms in turn,
grouping them into short sections of related procedures and forms.
<<chp_4,Chapter 4>> describes operations for creating procedures and variable bindings;
<<chp_5,Chapter 5>>, program control operations;
<<chp_6,Chapter 6>>, operations on the various object types (including lists, numbers, and strings);
<<chp_7,Chapter 7>>, input and output operations;
<<chp_8,Chapter 8>>, syntactic extension;
<<chp_9,Chapter 9>>, record-type definitions;
<<chp_10,Chapter 10>>, libraries and top-level programs;
and <<chp_11,Chapter 11>>, exceptions and conditions.

第 <<chp_4,四章>> 到 <<chp_11,十一章>> 为本书的参考章节。
他们依次介绍了 Scheme 的每个原始（Primitive） _处理过程_ 和 _语法形式_，
并将相关联的 _处理过程_ 和 _语法形式_ 组织在较短的章节中。
<<chp_4,第四章>> - 创建 _处理过程_ 和 _变量绑定_ 的操作；
<<chp_5,第五章>> - 程序控制操作；
<<chp_6,第六章>> - 对各种对象类型（包括 _列表_、_数字_、_字符串_）的操作；
<<chp_7,第七章>> - 输入与输出操作；
<<chp_8,第八章>> - 扩展语法；
<<chp_9,第九章>> - _记录类型_ 的定义；
<<chp_10,第十章>> - 库和高级程序；
<<chp_11,第十一章>> - 异常和条件。

<<chp_12,Chapter 12>> contains a collection of example procedures, libraries, and programs,
each with a short overview, some examples of its use,
the implementation with brief explanation,
and a set of exercises for further work.
Each of these programs demonstrates a particular set of features,
and together they illustrate an appropriate style for programming in Scheme.

<<chp_12,第十二章>> 包含一组处理过程、库和程序的示例，
每一个示例都有一个简短的概述、一些使用例子、简要的实现说明，以及一系列用于进一步展开的习题。
每一个程序都演示了一组特定的特性，并一起展示了 Scheme 中一种恰当的编程风格。

Following <<chp_12,Chapter 12>> are
bibliographical references, answers to selected exercises,
a detailed description of the formal syntax of Scheme programs and data,
a concise summary of Scheme syntactic forms and procedures,
and the index.
The summary of forms and procedures
is a useful first stop
for programmers
unsure of the structure of a syntactic form
or the arguments expected by a primitive procedure.
The page numbers
appearing in the summary of forms and procedures
and the italicized page numbers
appearing in the index
indicate the locations in the text
where forms and procedures are defined.

在 <<chp_12,第十二章>> 后面的是参考文献、习题答案、对 Scheme 程序和数据的正式语法的详细描述、
对 Scheme _语法形式_ 和 _处理过程_ 的简要总结，以及索引。
对 _语法形式_ 和 _处理过程_ 的总结，对于不确定 _语法形式_ 的结构或原始 _处理过程_ 的期望参数的程序员来说，
是一个有益的开始。在 <对语法形式和处理过程的总结> 中出现的页码，和在 <索引> 中出现的斜体页码，
表示 _语法形式_ 和 _处理过程_ 在本书中定义的位置。

Because the reference portion describes
a number of aspects of the language
not covered by the introductory chapters
along with a number of interesting short examples,
most readers will find it profitable
to read through most of the material
to become familiar with
each feature and how it relates to other features.
<<chp_6,Chapter 6>> is lengthy, however, and may be skimmed and later referenced as needed.

通过一些有趣的简短示例，参考章节描述了在入门章节中未涵盖到的该语言的许多方面，
因此，大多数读者会发现，通读大部分材料以熟悉每个特性及其与其他特性之间的联系，将会获益良多。
但是，<<chp_6,第六章>> 的篇幅很长，可以略读一下，以后再根据需要查阅。

An online version of this book is available at http://www.scheme.com/tspl/.
The summary of forms
and index
in the online edition
include page numbers for the printed version
and are thus useful as searchable indexes.

本书的在线版本可从 http://www.scheme.com/tspl/ 获得。
在线版本的 <语法形式总结> 和 <索引> 章节中包含印刷版的页码，因此可作为可查询的索引使用。

_About the illustrations_:
The cover illustration and
the illustration at the front of each chapter
are algorithmic line fields
created by artist Jean-Pierre Hébert,
based on an idea inspired by the writings of John Cage.
Each line field is created by the composition
of any number of grids of parallel lines.
The grids are regular, but they are not.
For instance, the lines are of irregular length, which creates ragged edges.
Their tone and thickness vary slightly.
They are not exactly equidistant.
They intersect with each other at a certain angle.
When this angle is small, patterns of interference develop.
The lines are first steeped into various scalar fields
that perturb their original straight shape,
then projected on the plane of the paper.
Masks introduce holes in some layers.
For the cover illustration, the grids are colored in different hues.

_关于插图_ :
封面插画和每章开头的插图是艺术家 Jean-Pierre Hébert 受 John Cage 的著作启发而创建的算法 _线场_。
每个线场都是由任意数量的平行线网格组成的。网格是规则的，但线场不是。
比如，线条的长度不规则，会出现参差不齐的边缘；
它们的色调和宽度略有不同；它们不是完全等距的；
它们以一定角度彼此相交，当该角度较小时，会产生干涉图案。
这些线条首先浸入各种标量场以扰乱其原始的笔直形状，然后投射到纸面上，
遮罩则会在层中造成空洞。在封面插画中，网格是以不同的颜色着色的。

All the images are created by a single Scheme program
that makes most of the decisions, based heavily on chance.
The artist controls only canvas size, aspect ratio, the overall palette of colors,
and levels of chance and fuzziness.
The task of the artist is
to introduce just enough chance at the right place
so that the results are at the same time surprising, interesting,
and in line with the artist's sense of aesthetics.
This is a game of uncertainty, chaos, and harmony.

所有图像都是由单个 Scheme 程序创建的，该程序在很大程度上是基于偶然性来做出大多数决策的。
艺术家仅需控制画布的大小、宽高比、整体色彩以及偶然性和模糊性的程度。
艺术家的任务则是在适当的地方引入足够的偶然性，以使结果能够同时让人感到惊奇、有趣且又符合艺术家的审美观。
这是一个充满不确定性的、混乱的、和谐的游戏。

_Acknowledgments_:
Many individuals contributed in one way or another
to the preparation of one or more editions of this book,
including Bruce Smith, Eugene Kohlbecker, Matthias Felleisen,
Dan Friedman, Bruce Duba, Phil Dybvig, Guy Steele, Bob Hieb,
Chris Haynes, Dave Plaisted, Joan Curry, Frank Silbermann,
Pavel Curtis, John Wait, Carl Bruggeman, Sam Daniel, Oscar Waddell,
Mike Ashley, John LaLonde, John Zuckerman, John Simmons,
Bob Prior, Bob Burger, and Aziz Ghuloum.
Many others have offered minor corrections and suggestions.
Oscar Waddell helped create the typesetting system
used to format the printed and online versions of this book.
A small amount of text and a few examples
have been adapted from the Revised^6^ Report for this book,
for which credit goes to
the editors of that report
and many others who contributed to it.
Finally and most importantly, my wife, Susan Dybvig,
suggested that I write this book in the first place
and lent her expertise and assistance
to the production and publication of this and the previous editions.

_致谢_ :
许多人以这种或那种方式为本书的一个或多个版本的准备工作做出了贡献，包括
Bruce Smith、Eugene Kohlbecker、Matthias Felleisen、Dan Friedman、Bruce Duba、Phil Dybvig、
Guy Steele、Bob Hieb、Chris Haynes、Dave Plaisted、Joan Curry、Frank Silbermann、Pavel Curtis、
John Wait、Carl Bruggeman、Sam Daniel、Oscar Waddell、Mike Ashley、John LaLonde、John Zuckerman、
John Simmons、Bob Prior、Bob Burger 和 Aziz Ghuloum。
许多其他人也提出了一些小的更正和建议。
Oscar Waddell 帮助创建了用于对本书的印刷版和在线版进行格式化的排版系统。
本书改编了《修订报告^6^》中的少量内容和一些示例，该报告的编辑者们和许多对其做出过贡献的人都对此表示赞赏。
最后也是最重要的一点，是我的妻子 Susan Dybvig 建议我先写这本书，
并借用她的专业技能和协助来完成了该版本及其先前版本的制作和发行。
