# https://rust-lang.github.io/mdBook/format/config.html
[book]
title = "程序设计方法 (第二版)"
language = "zh"
src = "src/zh"
authors = ["flytreeleft"]
multilingual = true

[build]

[output.html]
additional-css = ["theme/manual-fonts.css", "theme/racket.css", "theme/manual-racket.css", "theme/custom.css"]

[output.html.search]
limit-results = 15
